Title: ZID Charts
Airports:
  Bravo:
    - CVG
  Charlie:
    - CMH
    - EVV
    - IND
    - LEX
    - SDF
  Delta:
    - TZR
    - LOU
    - CRW
    - MIE
    - FTK
    - HUF
    - HTS
    - LUK
    - OSU
    - PKB
    - LCK
    - ILN
    - FFO
